### ISSUE TITLE
NextJs Usercentrics

### ISSUE THREAD

**Issue by Mar0cas** [s-group-dev/react-usercentrics#5]
Hello, i just want to ask, if works in NextJs applications?

**Comment by zwaardje** [comment]
Works like a charm, just set the time out for the load to be postponed

**Comment by Erythros** [comment]
> Works like a charm, just set the time out for the load to be postponed

Hi @zwaardje 
Do you have by any chance a running example?

**Comment by iiroj** [comment]
Thank you for the example. I will now close this issue as resolved. 👍
