### ISSUE TITLE
Unable to find available languages using given settingsId and version.

### ISSUE THREAD

**Issue by Erythros** [s-group-dev/react-usercentrics#6]
I'm using the library with NextJs in a similar way as explained by https://github.com/s-group-dev/react-usercentrics/issues/5
```ts
// _app.tsx

        <div>
            <UsercentricsScript
                settingsId={envVars.get("NEXT_PUBLIC_USERCENTRICS_ID")}
                version="production"
            />
            <UsercentricsProvider windowEventName="ucEvent">
                <MatomoProvider value={instance}>
                    <MatomoClient />
                    <Component {...pageProps} />
                </MatomoProvider>
            </UsercentricsProvider>
        </div>
```

On local, with `version="preview"` it does show the cookie consent with dummy data (I guess that's why it's preview).
However, on production, I'm running into
```
errorMessage:  "Unable to find available languages using given settingsId and version."

statusCode:  403
```
The main problem being with calling `GET https://api.usercentrics.eu/settings/{:id}/production/languages.json` (403)

Any advice?

**Comment by iiroj** [comment]
This seems like an issue with Usercentrics configuration. 🤔 This package doesn't do anything with languages explicitly.

**Comment by Erythros** [comment]
Yeah, I don't exactly know what's going on.

I ended up using the `Script` tag from NextJs. Something like 
```ts
            <Script
                src="https://app.usercentrics.eu/latest/main.js"
                id={envVars.get("NEXT_PUBLIC_USERCENTRICS_ID")}
            />
```

This seems to work. However, with the library I couldn't get it up and running.

**Comment by iiroj** [comment]
The script component is pretty simple:

https://github.com/s-group-dev/react-usercentrics/blob/0f823288294b91eed763f656eaa9e2b88027c18b/src/components/UsercentricsScript.tsx#L18-L26

Could it be the `async` attribute? I believe that is from the Usercentrics docs.

**Comment by iiroj** [comment]
What's the difference between using `id` and `data-settings-id`? 🤔

**Comment by iiroj** [comment]
Closing since I assume you figured it out.
